[tools]
terraform      = "1.9.8"
pre-commit     = "4.2.0"
terraform-docs = "0.20.0"
trivy          = "0.63.0"
tflint         = "0.58.0"
gitleaks       = "8.26.0"
shellcheck     = "0.10.0"

[tasks]
[tasks.fmt]
run = "terraform fmt -recursive"

[tasks.pre-commit]
run = "pre-commit run --all-files --show-diff-on-failure"

[tasks.trivy]
run = "trivy fs --scanners misconfig,secret,vuln ."

[tasks.shellcheck]
run = "shellcheck -S warning ./userdata/*.sh.tpl"
